language: java

jdk:
  - openjdk8

os:
  - linux

services:
  - docker

before_install:
  - sudo apt-get -y install jq netcat
  - sudo apt-get -y install mosquitto-clients
  - openssl aes-256-cbc -K $encrypted_e1b0a72f7201_key -iv $encrypted_e1b0a72f7201_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mkdir -p $HOME/.aws
  - cp aws_config $HOME/.aws/config
  - cp aws_credentials $HOME/.aws/credentials

# Skipped tests:

# Require aws credentials
# connect-aws-cloudwatch-source
# connect-aws-dynamodb-sink
# connect-aws-kinesis-source
# connect-aws-lambda-sink
# connect-aws-redshift-sink

# Require azure cli to login
# connect-azure-blob-storage-sink
# connect-azure-data-lake-storage-gen1-sink
# connect-azure-data-lake-storage-gen2-sink

# Require keyfile.json
# connect-gcp-bigquery-sink
# connect-gcp-firebase-sink
# connect-gcp-firebase-source
# connect-gcp-pubsub-source
# connect-gcs-sink
# connect-gcs-source
# connect-google-cloud-functions-sink
# connect-sqs-source

# Require to download TIB_ems-ce_8.5.1_linux_x86_64.zip
# connect-tibco-sink
# connect-tibco-source
# connect-jms-tibco-sink
# connect-jms-tibco-source

# Require to download and build images
# connect-jdbc-oracle11-sink
# connect-jdbc-oracle11-source
# connect-jdbc-oracle12-sink
# connect-jdbc-oracle12-source

jobs:
  include:
  # - name: "CONNECT: connect-active-mq-sink connect-active-mq-source connect-cassandra-sink connect-couchbase-sink connect-couchbase-source"
  #   env: TEST_LIST="connect/connect-active-mq-sink connect/connect-active-mq-source connect/connect-cassandra-sink connect/connect-couchbase-sink connect/connect-couchbase-source"

  # - name: "CONNECT: connect-debezium-mongodb-source connect-debezium-mysql-source connect-debezium-postgresql-source connect-debezium-sqlserver-source connect-elasticsearch-sink"
  #   env: TEST_LIST="connect/connect-debezium-mongodb-source connect/connect-debezium-mysql-source connect/connect-debezium-postgresql-source connect/connect-debezium-sqlserver-source connect/connect-elasticsearch-sink"

  # - name: "CONNECT: connect-hbase-sink connect-hdfs2-sink connect-hdfs3-sink connect-hdfs3-source connect-http-sink"
  #   env: TEST_LIST="connect/connect-hbase-sink connect/connect-hdfs2-sink connect/connect-hdfs3-sink connect/connect-hdfs3-source connect/connect-http-sink"

  - name: "CONNECT: connect-ibm-mq-sink connect-ibm-mq-source connect-influxdb-sink connect-influxdb-source connect-jdbc-mysql-sink"
    env: TEST_LIST="connect/connect-ibm-mq-sink connect/connect-ibm-mq-source connect/connect-influxdb-sink connect/connect-influxdb-source connect/connect-jdbc-mysql-sink"

  # - name: "CONNECT: connect-jdbc-mysql-source connect-jdbc-postgresql-sink connect-jdbc-postgresql-source connect-jdbc-sqlserver-sink connect-jdbc-sqlserver-source"
  #   env: TEST_LIST="connect/connect-jdbc-mysql-source connect/connect-jdbc-postgresql-sink connect/connect-jdbc-postgresql-source connect/connect-jdbc-sqlserver-sink connect/connect-jdbc-sqlserver-source"

  # - name: "CONNECT: connect-jms-active-mq-sink connect-jms-solace-sink connect-kudu-sink connect-kudu-source connect-mongodb-sink"
  #   env: TEST_LIST="connect/connect-jms-active-mq-sink connect/connect-jms-solace-sink connect/connect-kudu-sink connect/connect-kudu-source connect/connect-mongodb-sink"

  # - name: "CONNECT: connect-mongodb-source connect-mqtt-sink connect-mqtt-source connect-neo4j-sink connect-omnisci-sink"
  #   env: TEST_LIST="connect/connect-mongodb-source connect/connect-mqtt-sink connect/connect-mqtt-source connect/connect-neo4j-sink connect/connect-omnisci-sink"

  # - name: "CONNECT: connect-rabbitmq-source connect-redis-sink connect-replicator connect-s3-sink connect-s3-source"
  #   env: TEST_LIST="connect/connect-rabbitmq-source connect/connect-redis-sink connect/connect-replicator connect/connect-s3-sink connect/connect-s3-source"

  # - name: "CONNECT: connect-sftp-sink connect-sftp-source connect-solace-sink connect-solace-source connect-splunk-sink"
  #   env: TEST_LIST="connect/connect-sftp-sink connect/connect-sftp-source connect/connect-solace-sink connect/connect-solace-source connect/connect-splunk-sink"

  # - name: "CONNECT: connect-splunk-source connect-spool-dir-source connect-syslog-source"
  #   env: TEST_LIST="connect/connect-splunk-source connect/connect-spool-dir-source connect/connect-syslog-source"

  - name: "CONNECT (AWS): connect-aws-cloudwatch-source connect-aws-dynamodb-sink connect-aws-kinesis-source connect-aws-lambda-sink connect-aws-redshift-sink"
    env: TEST_LIST="connect/connect-aws-cloudwatch-source connect/connect-aws-dynamodb-sink connect/connect-aws-kinesis-source connect/connect-aws-lambda-sink connect/connect-aws-redshift-sink"

  - name: "CONNECT (GCP): connect-gcp-bigquery-sink connect-gcp-firebase-sink connect-gcp-firebase-source connect-gcp-pubsub-source connect-gcs-sink connect-gcs-source connect-google-cloud-functions-sink connect-sqs-source"
    env: TEST_LIST="connect/connect-gcp-bigquery-sink connect/connect-gcp-firebase-sink connect/connect-gcp-firebase-source connect/connect-gcp-pubsub-source connect/connect-gcs-sink connect/connect-gcs-source connect/connect-google-cloud-functions-sink connect/connect-sqs-source"

  # - name: "OTHER: connect-override-policy-sftp-sink connect-override-policy-sftp-source"
  #   env: TEST_LIST="other/connect-override-policy-sftp-sink other/connect-override-policy-sftp-source"

  # - name: "REPLICATOR: connect executable"
  #   env: TEST_LIST="replicator/connect replicator/executable"

script:
    - bash scripts/run-tests.sh "$TEST_LIST"
