language: java

jdk:
  - openjdk8

os:
  - linux

services:
  - docker

before_install:
  - sudo apt-get -y install netcat expect
  - openssl aes-256-cbc -K $encrypted_e1b0a72f7201_key -iv $encrypted_e1b0a72f7201_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mkdir -p $HOME/.aws
  - cp aws_config $HOME/.aws/config
  - cp aws_credentials $HOME/.aws/credentials
  - mkdir -p $HOME/.ccloud
  - cp config.cc.vsaboulin.travis $HOME/.ccloud/config
  - curl -L https://cnfl.io/ccloud-cli | sudo sh -s -- -b /usr/local/bin

# Skipped tests:

# Reason: Need to manually create a redshift cluster
# connect-aws-redshift-sink

# Reason: Require azure cli to login
# connect-azure-blob-storage-sink
# connect-azure-data-lake-storage-gen1-sink
# connect-azure-data-lake-storage-gen2-sink

# Require to download TIB_ems-ce_8.5.1_linux_x86_64.zip
# connect-tibco-sink
# connect-tibco-source
# connect-jms-tibco-sink
# connect-jms-tibco-source

# Require to download and build images
# connect-jdbc-oracle11-sink
# connect-jdbc-oracle11-source
# connect-jdbc-oracle12-sink
# connect-jdbc-oracle12-source

# Not reliable
# replicator/executable
# kudu-sink kudu-source ("Error connecting: TTransportException, TSocket read 0 bytes")

jobs:
  include:
  - name: "CONNECT: active-mq-sink active-mq-source cassandra-sink couchbase-sink couchbase-source debezium-mongodb-source debezium-mysql-source debezium-postgresql-source debezium-sqlserver-source elasticsearch-sink hbase-sink hdfs2-sink"
    env: TEST_LIST="connect/connect-active-mq-sink connect/connect-active-mq-source connect/connect-cassandra-sink connect/connect-couchbase-sink connect/connect-couchbase-source connect/connect-debezium-mongodb-source connect/connect-debezium-mysql-source connect/connect-debezium-postgresql-source connect/connect-debezium-sqlserver-source connect/connect-elasticsearch-sink connect/connect-hbase-sink connect/connect-hdfs2-sink"

  - name: "CONNECT: hdfs3-sink hdfs3-source http-sink ibm-mq-sink ibm-mq-source influxdb-sink influxdb-source jdbc-mysql-sink jdbc-mysql-source jdbc-postgresql-sink jdbc-postgresql-source jdbc-sqlserver-sink"
    env: TEST_LIST="connect/connect-hdfs3-sink connect/connect-hdfs3-source connect/connect-http-sink connect/connect-ibm-mq-sink connect/connect-ibm-mq-source connect/connect-influxdb-sink connect/connect-influxdb-source connect/connect-jdbc-mysql-sink connect/connect-jdbc-mysql-source connect/connect-jdbc-postgresql-sink connect/connect-jdbc-postgresql-source connect/connect-jdbc-sqlserver-sink"

  - name: "CCLOUD ccloud-demo CONNECT: jdbc-sqlserver-source jms-active-mq-sink jms-solace-sink mongodb-sink mongodb-source mqtt-sink mqtt-source neo4j-sink omnisci-sink rabbitmq-source redis-sink replicator"
    env: TEST_LIST="ccloud/ccloud-demo connect/connect-jdbc-sqlserver-source connect/connect-jms-active-mq-sink connect/connect-jms-solace-sink connect/connect-mongodb-sink connect/connect-mongodb-source connect/connect-mqtt-sink connect/connect-mqtt-source connect/connect-neo4j-sink connect/connect-omnisci-sink connect/connect-rabbitmq-source connect/connect-redis-sink connect/connect-replicator"

  - name: "CONNECT: sftp-sink sftp-source solace-sink solace-source splunk-sink splunk-source spool-dir-source syslog-source OTHER: override-policy-sftp-sink override-policy-sftp-source aws-cloudwatch-source aws-dynamodb-sink aws-kinesis-source aws-lambda-sink connect/connect-aws-cloudwatch-source connect/connect-aws-dynamodb-sink connect/connect-aws-kinesis-source connect/connect-aws-lambda-sink"
    env: TEST_LIST="connect/connect-sftp-sink connect/connect-sftp-source connect/connect-solace-sink connect/connect-solace-source connect/connect-splunk-sink connect/connect-splunk-source connect/connect-spool-dir-source connect/connect-syslog-source other/connect-override-policy-sftp-sink other/connect-override-policy-sftp-source"

  - name: "CONNECT: aws-sqs-source aws-s3-sink aws-s3-source gcp-bigquery-sink gcp-firebase-sink gcp-firebase-source gcp-pubsub-source gcs-sink gcs-source google-cloud-functions-sink REPLICATOR: connect"
    env: TEST_LIST="connect/connect-aws-sqs-source connect/connect-aws-s3-sink connect/connect-aws-s3-source connect/connect-gcp-bigquery-sink connect/connect-gcp-firebase-sink connect/connect-gcp-firebase-source connect/connect-gcp-pubsub-source connect/connect-gcp-gcs-sink connect/connect-gcp-gcs-source connect/connect-gcp-cloud-functions-sink replicator/connect"

script:
    - bash scripts/run-tests.sh "$TEST_LIST"
