language: bash

services:
  - docker

os:
  - osx

addons:
  homebrew:
    packages:
    - jq
    - mosquitto
    - awscli
    - azurecli

# before_script:
#     - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

script:
    - sh scripts/run-tests.sh

