language: bash

os:
  - linux

services:
  - docker

before_install:
  - sudo apt-get -y install jq
  - sudo apt-get -y install mosquitto-clients

jobs:
  include:
  # tips: in vs code ctrl j
  - name: "Connect tests #1"
    env: TEST_LIST="connect/connect-active-mq-source connect/connect-aws-cloudwatch-source connect/connect-aws-dynamodb-sink connect/connect-aws-lambda-sink connect/connect-aws-redshift-sink connect/connect-azure-blob-storage-sink connect/connect-azure-data-lake-storage-gen1-sink connect/connect-cassandra-sink connect/connect-couchbase-sink connect/connect-couchbase-source"
  - name: "Connect tests #2"
    env: TEST_LIST="connect/connect-debezium-mongodb-source connect/connect-debezium-mysql-source connect/connect-debezium-postgresql-source connect/connect-debezium-sqlserver-source connect/connect-elasticsearch-sink connect/connect-gcp-bigquery-sink connect/connect-gcp-pubsub-source connect/connect-gcs-sink connect/connect-gcs-source connect/connect-google-cloud-functions-sink connect/connect-hbase-sink"
  - name: "Connect tests #3"
    env: TEST_LIST="connect/connect-hdfs3-source connect/connect-http-sink connect/connect-ibm-mq-sink connect/connect-ibm-mq-source connect/connect-influxdb-sink connect/connect-influxdb-source connect/connect-jdbc-mysql-sink connect/connect-jdbc-mysql-source connect/connect-jdbc-oracle11-sink connect/connect-jdbc-oracle11-source connect/connect-jdbc-postgresql-sink"
  - name: "Connect tests #4"
    env: TEST_LIST="connect/connect-jdbc-postgresql-source connect/connect-jdbc-sqlserver-sink connect/connect-jdbc-sqlserver-source connect/connect-jms-active-mq-sink connect/connect-jms-solace-sink connect/connect-jms-tibco-sink connect/connect-jms-tibco-source connect/connect-kinesis-source connect/connect-mongodb-sink connect/connect-mongodb-source connect/connect-mqtt-sink"
  - name: "Connect tests #5"
    env: TEST_LIST="connect/connect-mqtt-source connect/connect-neo4j-sink connect/connect-omnisci-sink connect/connect-rabbitmq-source connect/connect-redis-sink connect/connect-replicator connect/connect-s3-source connect/connect-sftp-sink connect/connect-sftp-source connect/connect-solace-source connect/connect-splunk-source"
  - name: "Connect tests #6"
    env: TEST_LIST="connect/connect-sqs-source connect/connect-syslog-source connect/connect-kudu-source connect/connect-kudu-sink connect/connect-spool-dir-source connect/connect-gcp-firebase-source connect/connect-gcp-firebase-sink connect/connect-hdfs3-sink connect/connect-s3-sink connect/connect-solace-sink connect/connect-splunk-sink"
  - name: "Connect tests #7"
    env: TEST_LIST="connect/connect-active-mq-sink connect/connect-hdfs2-sink connect/connect-azure-data-lake-storage-gen2-sink connect/connect-jdbc-oracle12-sink connect/connect-jdbc-oracle12-source connect/connect-tibco-sink connect/connect-tibco-source"

script:
    - bash scripts/run-tests.sh "$TEST_LIST"
