---
version: '3.5'
services:

  jms-client:
    build:
      context: ../../other/jms-client/jms-client/
      args:
        TAG: ${TAG}
    hostname: jms-client
    container_name: jms-clients
    volumes:
      - ../../environment/sasl-ssl/security:/etc/kafka/secrets
    depends_on:
      - broker

  connect:
    entrypoint: ["echo", "Service connect disabled"]
